
GET https://umashankar3imvbnjscprhnky.drops.nxtwave.tech/todos/?priority=HIGH

###
GET https://umashankar3imvbnjscprhnky.drops.nxtwave.tech/todos/2/

###
POST https://umashankar3imvbnjscprhnky.drops.nxtwave.tech/todos/
Content-Type:application/json 

{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}

###
PUT https://umashankar3imvbnjscprhnky.drops.nxtwave.tech/todos/2/
Content-Type:application/json 

{
  "status": "DONE"
}
###
DELETE https://umashankar3imvbnjscprhnky.drops.nxtwave.tech/todos/1/
